API_HOST_URL: 'https://courses.riyali.com/'
ENVIRONMENT_DISPLAY_NAME: 'Riyali'
PLATFORM_NAME: 'Riyali'
PLATFORM_DESTINATION_NAME: 'Riyali'
FEEDBACK_EMAIL_ADDRESS: 'info@riyali.com'
DEBUG: true
MY_VIDEOS_ENABLED: true
COURSE_VIDEOS_ENABLED: true
ANNOUNCEMENTS_ENABLED: true
DISCOVERY: { COURSE: {
  TYPE: 'native',
  SEARCH_ENABLED: true,
}
}
#COURSE_ENROLLMENT : { TYPE : 'native', SEARCH_BAR_ENABLED : true }
COURSE_SHARING_ENABLED: true
BADGES_ENABLED: true
DOWNLOAD_TO_SD_CARD_ENABLED: true
#COURSE_DATES_ENABLED: true
TAB_LAYOUTS_ENABLED: true
#OAUTH_ENFORCE_SECURE: true
PUSH_NOTIFICATIONS: true
USER_PROFILES_ENABLED: true

DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
CERTIFICATES_ENABLED: true

YOUTUBE_PLAYER: { ENABLED: true, API_KEY: AIzaSyDxUS5Gvotwd8fUUpf75uRvEaDqbEO8XuU }